extends: default

rules:
  # Allow longer lines for readability
  line-length:
    max: 120
    level: warning

  # Allow trailing spaces (often caused by editors)
  trailing-spaces:
    level: warning

  # Be more lenient with indentation
  indentation:
    spaces: 2
    indent-sequences: true

  # Don't require document start markers
  document-start:
    present: false

  # Allow empty values
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: false

  # Allow truthy values like 'yes', 'no'
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: false

  # Allow duplicate keys in examples
  key-duplicates:
    level: warning

  # Be lenient with comments
  comments:
    min-spaces-from-content: 1
    require-starting-space: false

  # Allow brackets and braces
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1 